import { PolicyPack } from "./type";
export const policies: PolicyPack[] = [
  {
    id: "1",
    name: "EU AI Act (Regulation 2024/1689)",
    description:
      "Comprehensive AI regulation establishing harmonized rules for AI systems across the European Union with risk-based approach",
    category: "AI Regulation",
    country: "European Union",
    projectsCompliant: 4,
    totalProjects: 8,
    isActive: false,
    tags: ["AI Regulation", "EU Compliance", "Data Protection"],
    icon: "🇪🇺",
    color: "bg-blue-600",
    disable: false,
    // type: 'Mandatory'
  },
  {
    id: "2",
    name: "ISO/IEC 42001",
    description:
      "International standard for AI management systems providing requirements and guidance for establishing, implementing, and maintaining AI management systems",
    category: "Standards",
    country: "International",
    projectsCompliant: 3,
    totalProjects: 5,
    isActive: false,
    tags: ["ISO", "Standards", "AI Management"],
    icon: "🌐",
    color: "bg-gray-600",
    disable: false,
    // type: 'Voluntary'
  },
  {
    id: "3",
    name: "New York City Local Law No. 144",
    description:
      "Policies and controls for employers required to produce a bias audit in compliance with New York City Local Law No. 144",
    category: "Hiring",
    country: "United States",
    state: "New York",
    projectsCompliant: 6,
    totalProjects: 9,
    isActive: false,
    tags: ["Hiring"],
    icon: "🏢",
    color: "bg-blue-500",
    disable: true,
    // type: 'Voluntary'
  },
  {
    id: "4",
    name: "NIST AI Risk Management Framework",
    description:
      "Operationalize the Measure function of the NIST AI Responsible",
    category: "Risk Management",
    country: "United States",
    projectsCompliant: 1,
    totalProjects: 3,
    isActive: true,
    tags: ["Risk Management"],
    icon: "🛡️",
    color: "bg-black",
    type: "Voluntary",
    disable: true,
  },
  {
    id: "5",
    name: "Colorado Senate Bill SB21-169",
    description:
      "Protects Colorado consumers from insurance practices that result in unfair discrimination",
    category: "Insurance",
    country: "United States",
    state: "Colorado",
    projectsCompliant: 11,
    totalProjects: 13,
    isActive: true,
    tags: ["Insurance"],
    icon: "🏛️",
    color: "bg-purple-500",
    type: "Mandatory",
    disable: true,
  },
  {
    id: "6",
    name: "SR 11-7",
    description:
      "Federal Reserve supervisory guidance on model risk management providing framework for financial institutions to identify, measure, monitor, and control model risk",
    category: "Financial Services",
    country: "United States",
    projectsCompliant: 7,
    totalProjects: 10,
    isActive: false,
    tags: ["Financial Services", "Model Risk", "Banking"],
    icon: "🏦",
    color: "bg-emerald-600",
    disable: true,
    // type: 'Mandatory'
  },
  {
    id: "7",
    name: "Canada AI and Data Act",
    description:
      "Canadian federal legislation regulating artificial intelligence and data systems to promote innovation while protecting Canadians from potential harms",
    category: "AI Regulation",
    country: "Canada",
    projectsCompliant: 3,
    totalProjects: 6,
    isActive: true,
    tags: ["AI Regulation", "Canadian Compliance", "Data Governance"],
    icon: "🇨🇦",
    color: "bg-red-500",
    disable: true,
    // type: 'Mandatory'
  },
  {
    id: "8",
    name: "California AB 2830",
    description:
      "California Assembly Bill addressing AI transparency and accountability requirements for automated decision-making systems",
    category: "AI Regulation",
    country: "United States",
    state: "California",
    projectsCompliant: 5,
    totalProjects: 8,
    isActive: true,
    tags: ["AI Regulation", "California", "Transparency"],
    icon: "🐻",
    color: "bg-yellow-600",
    disable: true,
    // type: 'Mandatory'
  },
  {
    id: "9",
    name: "Colorado AI Act SB 205",
    description:
      "Colorado Senate Bill 205 regulating high-risk artificial intelligence systems to prevent algorithmic discrimination",
    category: "AI Regulation",
    country: "United States",
    state: "Colorado",
    projectsCompliant: 4,
    totalProjects: 7,
    isActive: false,
    tags: ["AI Regulation", "Colorado", "Algorithmic Bias"],
    icon: "⛰️",
    color: "bg-indigo-600",
    disable: true,
    // type: 'Voluntary'
  },
  {
    id: "10",
    name: "Colorado SB 21-169",
    description:
      "Colorado legislation addressing insurance discrimination and algorithmic accountability in insurance practices",
    category: "Insurance",
    country: "United States",
    state: "Colorado",
    projectsCompliant: 8,
    totalProjects: 11,
    isActive: true,
    tags: ["Insurance", "Colorado", "Discrimination"],
    icon: "🏔️",
    color: "bg-blue-700",
    disable: true,
    // type: 'Mandatory'
  },
  {
    id: "11",
    name: "Illinois HB 3773",
    description:
      "Illinois House Bill establishing requirements for artificial intelligence systems used in employment decisions",
    category: "Employment",
    country: "United States",
    state: "Illinois",
    projectsCompliant: 6,
    totalProjects: 9,
    isActive: true,
    tags: ["Employment", "Illinois", "AI Ethics"],
    icon: "🌾",
    color: "bg-orange-600",
    disable: true,
    // type: 'Mandatory'
  },
  {
    id: "12",
    name: "EEOC Technical Assistance on ADA and AI",
    description:
      "Guidance from the technical assistance document issued by the U.S. Equal Employment Opportunity",
    category: "Employment",
    country: "United States",
    projectsCompliant: 9,
    totalProjects: 9,
    isActive: true,
    tags: ["Employment"],
    icon: "⚖️",
    color: "bg-green-500",
    type: "Mandatory",
    disable: true,
  },

  {
    id: "13",
    name: "NYC LL 144",
    disable: true,
    description:
      "New York City Local Law 144 requiring bias audits for automated employment decision tools",
    category: "Employment",
    country: "United States",
    state: "New York",
    projectsCompliant: 7,
    totalProjects: 10,
    isActive: true,
    tags: ["Employment", "NYC", "Bias Audit"],
    icon: "🗽",
    color: "bg-slate-600",
    // type: 'Mandatory'
  },
  {
    id: "14",
    name: "NY State A00667",
    description:
      "New York State Assembly Bill addressing algorithmic accountability and transparency in automated decision systems",
    category: "AI Regulation",
    country: "United States",
    state: "New York",
    projectsCompliant: 2,
    totalProjects: 4,
    isActive: false,
    tags: ["AI Regulation", "New York", "Algorithmic Accountability"],
    icon: "🍎",
    color: "bg-red-600",
    disable: true,
    // type: 'Voluntary'
  },
  {
    id: "15",
    name: "Utah SB 149",
    description:
      "Utah Senate Bill 149 establishing governance framework for artificial intelligence systems in government operations",
    category: "Government",
    country: "United States",
    state: "Utah",
    projectsCompliant: 3,
    totalProjects: 6,
    isActive: true,
    tags: ["Government", "Utah", "AI Governance"],
    icon: "🏜️",
    color: "bg-amber-600",
    disable: true,
    // type: 'Mandatory'
  },
  {
    id: "16",
    name: "South Korea AI Basic Act",
    description:
      "South Korean comprehensive legislation establishing fundamental framework for AI development, use, and governance",
    category: "AI Regulation",
    country: "South Korea",
    projectsCompliant: 1,
    totalProjects: 3,
    isActive: false,
    tags: ["AI Regulation", "South Korea", "AI Framework"],
    icon: "🇰🇷",
    color: "bg-teal-600",
    disable: true,
    // type: 'Voluntary'
  },
];
