export const aiPolicyData = [
  {
    id: 1,
    policyName: "Removing Barriers to American Leadership in Artificial Intelligence (Executive Order)",
    shortName: "US AI Leadership EO",
    region: "United States",
    effectiveDate: "2025-01-23",
    lastUpdated: "2025-01-23",
    status: "Active",
    country: "United States",
    state: "National",
    legalStatus: "Enacted",
    timeline: "Signed January 23, 2025; 180-day deadline for Action Plan submission (July 22, 2025); immediate review and revocation of prior orders",
    sources: "https://www.softwareimprovementgroup.com/us-ai-legislation-overview/",
    summary: "This executive order revokes previous federal AI policies deemed to hinder U.S. AI innovation, mandates the development of a new national AI strategy focused on economic competitiveness and national security, and requires all federal AI systems to be \"free from ideological bias or engineered social agendas.\" It directs a cross-agency team to submit an implementation plan within 180 days and to suspend, revise, or rescind conflicting prior actions.",
    whoIsAffected: "Federal government agencies, contractors developing AI for federal use, indirectly tech companies supplying federal AI systems",
    howTheyAreAffected: "Agencies must review and align their AI systems and procurement to ensure ideological neutrality, remove DEI (diversity, equity, inclusion) requirements, and comply with new strategic priorities. Contractors may face new requirements for system documentation and reporting.",
    impact: "Quantified data not available; expected to reduce compliance costs for federal contractors by eliminating certain reporting and DEI requirements; potential market expansion for vendors aligned with new federal priorities.",
    complianceRequirements: "Agencies must conduct internal reviews, document compliance with the new order, submit implementation plans, and adjust procurement and reporting processes. Contractors may need to update documentation to demonstrate compliance.",
    enforcementDetails: "Oversight by the President's advisors on science, technology, AI, crypto, national security, economic and domestic policy; enforcement through agency compliance reviews and procurement audits. No specific penalty amounts disclosed."
  },
  {
    id: 2,
    policyName: "Arkansas HB 1958 – AI Use Policy for Public Entities",
    shortName: "Arkansas AI Use Policy",
    region: "Arkansas, US",
    effectiveDate: "2025-08-03",
    lastUpdated: "2025-07-01",
    status: "Active",
    country: "United States",
    state: "Arkansas",
    legalStatus: "Enacted",
    timeline: "Signed July 2025; Effective August 3, 2025",
    sources: "https://www.whitecase.com/insight-alert/california-kentucky-tracking-rise-state-ai-laws-2025",
    summary: "Requires all public entities in Arkansas to develop and adopt a comprehensive policy governing the authorized use of AI and Automated Decision-Making Technologies (ADMT).",
    whoIsAffected: "State and local government agencies, public schools, higher education institutions",
    howTheyAreAffected: "Must create, document, and implement internal AI use policies specifying permitted applications, oversight, and risk management.",
    impact: "No quantified cost data available; expected to increase administrative workload for public entities. Non-compliance could result in administrative penalties or loss of funding.",
    complianceRequirements: "Drafting of AI use policies, staff training, regular review and updates, documentation of AI systems in use.",
    enforcementDetails: "Oversight by state executive agencies; compliance monitored through audits and reporting. Penalties not specified."
  },
  {
    id: 3,
    policyName: "Arkansas HB 1876 – Ownership of Generative AI Content and Models",
    shortName: "Arkansas AI Content Ownership",
    region: "Arkansas, US",
    effectiveDate: "2025-08-03",
    lastUpdated: "2025-07-01",
    status: "Active",
    country: "United States",
    state: "Arkansas",
    legalStatus: "Enacted",
    timeline: "Signed July 2025; Effective August 3, 2025",
    sources: "https://www.whitecase.com/insight-alert/california-kentucky-tracking-rise-state-ai-laws-2025",
    summary: "Establishes that individuals providing input to generative AI tools own the resulting content, provided it does not infringe on existing IP rights. Individuals (excluding employees) who provide data for AI model training own the resulting trained model, unless data was unlawfully obtained.",
    whoIsAffected: "Individuals, businesses, AI developers, data contributors",
    howTheyAreAffected: "Must recognize and respect new ownership rights for AI-generated content and trained models; may need to update contracts and data handling practices.",
    impact: "No quantified cost or penalty data available; potential for increased litigation or contract renegotiation costs.",
    complianceRequirements: "Documentation of data provenance, updated terms of service, clear attribution of ownership in contracts.",
    enforcementDetails: "Enforced through state courts; remedies include injunctions and damages for violations. No specific penalty amounts disclosed."
  },
  {
    id: 4,
    policyName: "Kentucky SB 4 – AI Policy Standards for State Use",
    shortName: "Kentucky AI Standards",
    region: "Kentucky, US",
    effectiveDate: "2025-08-03",
    lastUpdated: "2025-07-01",
    status: "Active",
    country: "United States",
    state: "Kentucky",
    legalStatus: "Enacted",
    timeline: "Signed July 2025; Effective August 3, 2025",
    sources: "https://www.whitecase.com/insight-alert/california-kentucky-tracking-rise-state-ai-laws-2025",
    summary: "Directs the Commonwealth Office of Technology to develop and implement policy standards for the use of AI by state agencies.",
    whoIsAffected: "State government agencies, contractors providing AI solutions to the state",
    howTheyAreAffected: "Must comply with new policy standards, including possible requirements for risk assessment, transparency, and oversight.",
    impact: "No quantified cost or penalty data available; may increase compliance and documentation costs for agencies and vendors.",
    complianceRequirements: "Adoption of new policies, staff training, documentation of AI systems, periodic reviews.",
    enforcementDetails: "Oversight by the Commonwealth Office of Technology; compliance monitored through audits and reporting. Penalties not specified."
  },
  {
    id: 5,
    policyName: "Montana SB 212 – AI Risk Management for Critical Infrastructure",
    shortName: "Montana AI Risk Management",
    region: "Montana, US",
    effectiveDate: "2025-08-03",
    lastUpdated: "2025-07-01",
    status: "Active",
    country: "United States",
    state: "Montana",
    legalStatus: "Enacted",
    timeline: "Signed July 2025; Effective August 3, 2025",
    sources: "https://www.whitecase.com/insight-alert/california-kentucky-tracking-rise-state-ai-laws-2025",
    summary: "Requires critical infrastructure facilities controlled by AI systems to develop a risk management policy aligned with national or international AI risk management frameworks. Restricts government from limiting private computational resource ownership except for compelling interests.",
    whoIsAffected: "Critical infrastructure operators (energy, water, transportation, etc.), private owners of computational resources",
    howTheyAreAffected: "Must develop, document, and maintain AI risk management policies; subject to compliance checks.",
    impact: "No quantified cost or penalty data available; compliance may require hiring consultants or additional staff.",
    complianceRequirements: "Drafting and maintaining risk management policies, periodic risk assessments, documentation, and possible third-party audits.",
    enforcementDetails: "State regulatory agencies responsible for oversight; penalties for non-compliance not specified."
  },
  {
    id: 6,
    policyName: "European Union Artificial Intelligence Act (Regulation (EU) 2024/1689)",
    shortName: "EU AI Act",
    region: "European Union",
    effectiveDate: "2024-08-01",
    lastUpdated: "2024-07-15",
    status: "Active",
    country: "European Union (27 Member States)",
    state: "National (EU-wide)",
    legalStatus: "Enacted",
    timeline: "Adopted July 12, 2024; Effective August 1, 2024; Main provisions enforced from August 2, 2026",
    sources: "https://www.cimplifi.com/resources/the-updated-state-of-ai-regulations-for-2025/",
    summary: "Establishes harmonized, risk-based rules for AI across the EU. Prohibits certain AI uses (e.g., real-time biometric ID in public spaces, social scoring), imposes strict requirements on \"high-risk\" AI (risk management, data governance, transparency, human oversight, conformity assessments), and mandates registration and CE certification for high-risk AI systems.",
    whoIsAffected: "Tech companies, healthcare, finance, education, government, AI developers, importers, distributors",
    howTheyAreAffected: "Must classify AI systems by risk, comply with strict requirements for high-risk systems, register in EU database, obtain CE marking, and ensure ongoing monitoring and reporting.",
    impact: "Compliance costs for high-risk AI providers estimated in the hundreds of millions of euros EU-wide; penalties for non-compliance up to €35 million or 7% of global annual turnover (whichever is higher).",
    complianceRequirements: "Risk assessments, technical documentation, conformity assessments, registration, ongoing monitoring, incident reporting, staff training.",
    enforcementDetails: "National competent authorities in each member state, coordinated by the European Artificial Intelligence Board; penalties up to €35 million or 7% of global turnover; regular audits and market surveillance."
  },
  // {
  //   id: 7,
  //   policyName: "APAC AI Policies",
  //   region: "Asia-Pacific",
  //   effectiveDate: "2024-05-01",
  //   lastUpdated: "2024-07-20",
  //   status: "Active",
  //   impactOnSector: [
  //     "Diverse and fast-evolving landscape: Ranges from China's strict government control to Singapore's 'soft law' and voluntary frameworks",
  //     "Emphasis on data sovereignty: Many countries have data localization and privacy laws that affect where data can be stored and processed",
  //     "Focus on ethical guidelines and transparency: Countries like Japan and Singapore promote frameworks for responsible AI development and deployment"
  //   ],
  //   impactOnCountries: [
  //     "The variety of national policies requires companies to develop country-specific compliance strategies",
  //     "Policies are often intertwined with national interests, such as data security and economic growth"
  //   ],
  //   actionItems: [
  //     "Adhere to data localization laws in countries like China",
  //     "Adopt ethical frameworks and best practices for transparency and explainability, especially in markets like Singapore",
  //     "Stay informed on national strategies to identify new legal requirements and business opportunities"
  //   ]
  // }
  {
    id: 7,
    policyName: "California Consumer Privacy Protection Agency (CPPA) AI Rules",
    country: "United States",
    state: "California",
    legalStatus: "Proposed (pending final approval)",
    "Change Type": "Approaching Deadline",
    timeline: "Approved by CPPA board 2025-08-13; pending Office of Administrative Law approval; effective date expected 2025-10-01 (if filed in August), otherwise 2026-01-01",
    lastUpdated: "2025-08-13",
    sources: "https://www.orrick.com/en/Insights/2025/08/AI-Law-Center-August-2025-Updates",
    summary: "The CPPA unanimously approved new rules governing the use of AI and automated decision-making systems by businesses subject to the California Consumer Privacy Act (CCPA). The rules introduce new transparency, risk assessment, and consumer opt-out requirements for AI-driven profiling and decision-making.",
    whoIsAffected: "Businesses using AI for consumer profiling, automated decision-making, or targeted advertising in California; tech firms, e-commerce, financial services, and healthcare providers.",
    howTheyAreAffected: " - Required to provide detailed disclosures about AI use to consumers. - Must conduct and document risk assessments for high-risk AI applications. - Consumers must be given clear opt-out mechanisms for AI-driven decisions.",
    impact: " - Estimated compliance costs: $100,000–$500,000 per business for initial implementation. - Penalties: Up to $7,500 per violation. - Deadline for compliance: 2025-10-01 (if rules are filed in August).",
    complianceRequirements: " - Update privacy notices to include AI-specific disclosures. - Conduct and document AI risk assessments. - Implement opt-out mechanisms and consumer rights request processes.",
    enforcementDetails: " - Enforced by the California Consumer Privacy Protection Agency. - Penalties assessed per violation; enforcement actions may begin immediately after effective date."
  }
];
